application:
  bindAddress: :8449
  production : false
  debug      : false
authentication:
  authority: https://algotiqa:8443/auth/realms/algotiqa
messaging:
  address : rabbitmq:5672
  username: admin
  password: admin
  journal:
    directory      : journal
    queueSize      : 1000
    compactMessages: 1000
    dbSpoolInterval: 0
